#!/usr/bin/env node
/**
 * Script to compare capabilities generated by Python and JavaScript scripts.
 * 
 * Usage:
 *     node compare_capabilities.js <python_json> <javascript_json> [output_diff_file]
 * 
 * Example:
 *     node compare_capabilities.js output/onoff_python.json output/onoff_js.json output/diff.json
 */

const fs = require('fs');
const path = require('path');

function deepEqual(obj1, obj2, path = '') {
    const differences = [];
    
    if (obj1 === obj2) {
        return differences;
    }
    
    if (obj1 === null || obj2 === null) {
        if (obj1 !== obj2) {
            differences.push({
                path: path || 'root',
                python: obj1,
                javascript: obj2,
                message: `Value mismatch: ${obj1} vs ${obj2}`
            });
        }
        return differences;
    }
    
    if (typeof obj1 !== typeof obj2) {
        differences.push({
            path: path || 'root',
            python: obj1,
            javascript: obj2,
            message: `Type mismatch: ${typeof obj1} vs ${typeof obj2}`
        });
        return differences;
    }
    
    if (typeof obj1 !== 'object' || obj1 === null || obj2 === null) {
        if (obj1 !== obj2) {
            differences.push({
                path: path || 'root',
                python: obj1,
                javascript: obj2,
                message: `Value mismatch: ${obj1} vs ${obj2}`
            });
        }
        return differences;
    }
    
    if (Array.isArray(obj1) !== Array.isArray(obj2)) {
        differences.push({
            path: path || 'root',
            python: obj1,
            javascript: obj2,
            message: `Array vs Object mismatch`
        });
        return differences;
    }
    
    // Get all keys from both objects
    const allKeys = new Set([...Object.keys(obj1), ...Object.keys(obj2)]);
    
    for (const key of allKeys) {
        const currentPath = path ? `${path}.${key}` : key;
        
        if (!(key in obj1)) {
            differences.push({
                path: currentPath,
                python: undefined,
                javascript: obj2[key],
                message: `Key missing in Python: ${key}`
            });
            continue;
        }
        
        if (!(key in obj2)) {
            differences.push({
                path: currentPath,
                python: obj1[key],
                javascript: undefined,
                message: `Key missing in JavaScript: ${key}`
            });
            continue;
        }
        
        const nestedDiffs = deepEqual(obj1[key], obj2[key], currentPath);
        differences.push(...nestedDiffs);
    }
    
    return differences;
}

function normalizeForComparison(obj) {
    // Create a deep copy and normalize values
    if (obj === null || typeof obj !== 'object') {
        return obj;
    }
    
    if (Array.isArray(obj)) {
        return obj.map(normalizeForComparison);
    }
    
    const normalized = {};
    for (const [key, value] of Object.entries(obj)) {
        // Skip xmlSource as it may differ (file path vs URL)
        if (key === 'xmlSource') {
            continue;
        }
        
        // Normalize numeric strings and hex values
        if (typeof value === 'string') {
            // Try to normalize hex codes
            if (value.match(/^0x[0-9A-Fa-f]+$/)) {
                normalized[key] = value.toUpperCase();
            } else {
                normalized[key] = value;
            }
        } else if (typeof value === 'object' && value !== null) {
            normalized[key] = normalizeForComparison(value);
        } else {
            normalized[key] = value;
        }
    }
    
    return normalized;
}

function compareCapabilities(pythonFile, jsFile, outputDiffFile = null) {
    console.log(`Comparing capabilities:`);
    console.log(`  Python:   ${pythonFile}`);
    console.log(`  JavaScript: ${jsFile}`);
    console.log('');
    
    if (!fs.existsSync(pythonFile)) {
        console.error(`Error: Python JSON file not found: ${pythonFile}`);
        process.exit(1);
    }
    
    if (!fs.existsSync(jsFile)) {
        console.error(`Error: JavaScript JSON file not found: ${jsFile}`);
        process.exit(1);
    }
    
    // Read JSON files
    const pythonData = JSON.parse(fs.readFileSync(pythonFile, 'utf-8'));
    const jsData = JSON.parse(fs.readFileSync(jsFile, 'utf-8'));
    
    // Normalize for comparison
    const pythonNormalized = normalizeForComparison(pythonData);
    const jsNormalized = normalizeForComparison(jsData);
    
    // Compare
    const differences = deepEqual(pythonNormalized, jsNormalized);
    
    // Print results
    console.log('='.repeat(80));
    console.log('COMPARISON RESULTS');
    console.log('='.repeat(80));
    console.log('');
    
    if (differences.length === 0) {
        console.log('✅ SUCCESS: Files are identical!');
        console.log('');
        console.log(`Cluster: ${pythonData.name} (${pythonData.clusterId})`);
        if (pythonData.Capabilities?.Attributes) {
            console.log(`Attributes: ${Object.keys(pythonData.Capabilities.Attributes).length}`);
        }
        if (pythonData.Capabilities?.Commands) {
            console.log(`Commands: ${Object.keys(pythonData.Capabilities.Commands).length}`);
        }
        if (pythonData.Capabilities?.Features) {
            console.log(`Features: ${Object.keys(pythonData.Capabilities.Features).length}`);
        }
    } else {
        console.log(`❌ FOUND ${differences.length} DIFFERENCE(S):`);
        console.log('');
        
        // Group differences by category
        const missingInPython = differences.filter(d => d.python === undefined);
        const missingInJS = differences.filter(d => d.javascript === undefined);
        const valueMismatches = differences.filter(d => 
            d.python !== undefined && d.javascript !== undefined
        );
        
        if (missingInPython.length > 0) {
            console.log(`Missing in Python (${missingInPython.length}):`);
            missingInPython.slice(0, 10).forEach(diff => {
                console.log(`  - ${diff.path}: ${diff.message}`);
            });
            if (missingInPython.length > 10) {
                console.log(`  ... and ${missingInPython.length - 10} more`);
            }
            console.log('');
        }
        
        if (missingInJS.length > 0) {
            console.log(`Missing in JavaScript (${missingInJS.length}):`);
            missingInJS.slice(0, 10).forEach(diff => {
                console.log(`  - ${diff.path}: ${diff.message}`);
            });
            if (missingInJS.length > 10) {
                console.log(`  ... and ${missingInJS.length - 10} more`);
            }
            console.log('');
        }
        
        if (valueMismatches.length > 0) {
            console.log(`Value Mismatches (${valueMismatches.length}):`);
            valueMismatches.slice(0, 10).forEach(diff => {
                console.log(`  - ${diff.path}:`);
                console.log(`    Python:   ${JSON.stringify(diff.python)}`);
                console.log(`    JavaScript: ${JSON.stringify(diff.javascript)}`);
            });
            if (valueMismatches.length > 10) {
                console.log(`  ... and ${valueMismatches.length - 10} more`);
            }
            console.log('');
        }
        
        // Save diff file if requested
        if (outputDiffFile) {
            const diffReport = {
                summary: {
                    totalDifferences: differences.length,
                    missingInPython: missingInPython.length,
                    missingInJavaScript: missingInJS.length,
                    valueMismatches: valueMismatches.length
                },
                differences: differences,
                pythonFile: pythonFile,
                javascriptFile: jsFile
            };
            
            const outputDir = path.dirname(outputDiffFile);
            if (!fs.existsSync(outputDir)) {
                fs.mkdirSync(outputDir, { recursive: true });
            }
            
            fs.writeFileSync(outputDiffFile, JSON.stringify(diffReport, null, 2), 'utf-8');
            console.log(`Difference report saved to: ${outputDiffFile}`);
        }
    }
    
    console.log('');
    console.log('='.repeat(80));
    
    return differences.length === 0;
}

// Main function
function main() {
    if (process.argv.length < 4 || process.argv.length > 5) {
        console.error('Usage: node compare_capabilities.js <python_json> <javascript_json> [output_diff_file]');
        console.error('');
        console.error('Example:');
        console.error('  node compare_capabilities.js output/onoff_python.json output/onoff_js.json output/diff.json');
        process.exit(1);
    }
    
    const pythonFile = process.argv[2];
    const jsFile = process.argv[3];
    const outputDiffFile = process.argv[4] || null;
    
    const success = compareCapabilities(pythonFile, jsFile, outputDiffFile);
    process.exit(success ? 0 : 1);
}

if (require.main === module) {
    main();
}

module.exports = { compareCapabilities };
